// pages/index.tsx (Next.js App Router or SPA style)
"use client"
import { Button } from '@mui/material';
import React, { useState } from 'react';
// import { Button } from "@/components/ui/button"; // assuming you're using shadcn/ui or similar
import { ChevronDownIcon } from 'lucide-react';

export default function EditorPage() {
  const [title, setTitle] = useState("Welcome to the Future of Writing");
  const [description, setDescription] = useState("This is a bold new paragraph generated by our AI-assisted workflow. You can edit this on the left, and the results appear here in real time.");

  return (
    <div className="w-full h-screen flex overflow-hidden">
      {/* Left Panel */}
      <div className="w-1/3 bg-gray-100 p-6 flex flex-col justify-between border-r border-gray-300">
        <div className="space-y-4">
          {/* Dropdown Panels */}
          <Dropdown title="Tone">
            <select className="w-full border p-2 rounded">
              <option>Professional</option>
              <option>Friendly</option>
              <option>Creative</option>
            </select>
          </Dropdown>

          <Dropdown title="Audience">
            <select className="w-full border p-2 rounded">
              <option>General</option>
              <option>Developers</option>
              <option>Executives</option>
            </select>
          </Dropdown>

          <Dropdown title="Title Text">
            <input
              className="w-full border p-2 rounded"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
          </Dropdown>

          <Dropdown title="Paragraph Content">
            <textarea
              className="w-full border p-2 rounded h-28"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </Dropdown>
        </div>

        {/* Buttons */}
        <div className="flex justify-end space-x-2 pt-6">
          <Button variant="outlined">Cancel</Button>
          <Button>Confirm & Export</Button>
        </div>
      </div>

      {/* Right Panel */}
      <div className="flex-1 bg-white p-10 overflow-y-auto">
        <h1 className="text-3xl font-bold mb-4">{title}</h1>
        <p className="text-lg leading-relaxed text-gray-800">
          {description}
        </p>

        {/* Extra filler */}
        <div className="mt-8 space-y-6 text-gray-700">
          <p>
            Here's an additional paragraph to show how the formatting works. You can use this space to display structured output from your AI editor or copy templates.
          </p>
          <p>
            As you change content in the left panel, this space reflects those changes instantly. It’s ideal for emails, letters, reports, or content briefs.
          </p>
          <ul className="list-disc ml-6 mt-4">
            <li>Live previews</li>
            <li>Flexible templates</li>
            <li>Fast export workflows</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

function Dropdown({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border border-gray-300 rounded p-3 bg-white shadow-sm">
      <div className="flex items-center justify-between mb-2 text-sm font-semibold text-gray-700">
        {title}
        <ChevronDownIcon size={16} />
      </div>
      {children}
    </div>
  );
}
